[package]
name = "parser"
version = "0.1.0"
authors = ["jaankaup <janne.kauppinen4321@gmail.fi>"]
edition = "2021"

[lib]

[dependencies]

serde.workspace = true
serde_json.workspace = true
quick-xml.workspace = true
thiserror.workspace = true
